# Generated by Django 5.0.1 on 2024-02-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feature_product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Top_rated",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Top_selling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("price", models.IntegerField()),
            ],
        ),
    ]
