# Generated by Django 5.0.1 on 2024-02-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("best_offers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature_product",
            name="tags",
            field=models.CharField(
                choices=[("fp", "Feature Product"), ("bs", "Best Seller")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="top_rated",
            name="tags",
            field=models.CharField(
                choices=[("fp", "Feature Product"), ("bs", "Best Seller")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="top_selling",
            name="tags",
            field=models.CharField(
                choices=[("fp", "Feature Product"), ("bs", "Best Seller")],
                max_length=2,
                null=True,
            ),
        ),
    ]
