# Generated by Django 5.0.1 on 2024-02-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feature_products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.CharField(max_length=6),
        ),
    ]
